export const INITIALIZE_STATE = 'INITIALIZE_STATE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const ADD_EXERCISE_TO_LOCAL_DATA = 'ADD_EXERCISE_TO_LOCAL_DATA';
export const ADD_EXERCISE_TO_DB = 'ADD_EXERCISE_TO_DB';
export const DELETE_EXERCISE_FROM_LOCAL_DATA = 'DELETE_EXERCISE_FROM_LOCAL_DATA';
export const UPDATE_EXERCISE_IN_DB = 'UPDATE_EXERCISE_IN_DB';
export const UPDATE_EXERCISE_IN_LOCAL_DATA = 'UPDATE_EXERCISE_IN_LOCAL_DATA';

export const ADD_WORKOUT_TO_LOCAL_DATA = 'ADD_WORKOUT_TO_LOCAL_DATA';
export const ADD_WORKOUT_TO_DB = 'ADD_WORKOUT_TO_DB';
export const UPDATE_WORKOUT_IN_DB = 'UPDATE_WORKOUT_IN_DB';
export const UPDATE_WORKOUT_IN_LOCAL_DATA = 'UPDATE_WORKOUT_IN_LOCAL_DATA';

export const ADD_SET_TO_LOCAL_DATA = 'ADD_SET_TO_LOCAL_DATA';